source 'http://rubygems.org'

gem 'sinatra', '2.0.0'
gem 'json', '1.8.6'

group :test do
	gem 'cucumber', '1.2.1'
	gem 'rspec', '2.11.0'
	gem 'httparty', '0.8.3'
	gem 'childprocess', '0.7.0'
end