Feature: Change PIN
	As soon as the bank issues new cards to customers, they are supplied
	with a personal Identification Number (PIN) that is randomly 
	generated by the system
	
	In order to be able to change ti to something they can easily
	remember, customers with new bank cards need to be able to change 
	their PIN using the ATM
	
	Background: Insert a newly issued card and sign in
		Given I have been issued a new cards
		And I insert the cardn entering the correct PIN
		And I choose "Change PIN" from the menu
		
	Scenario: Change PIN succesfully
		And I change the PIN to 9876
		Then the system should remember my PIN is now 9876
		
	Scenario: Try to change PIN to the same as before
		And I try to change the PIN to the original PIN number
		Then I should see a waringing message
		And the system should not have changed my PIN